import type { EslintRules } from '../models'

import { jsxA11yRules } from './jsx-a11y'
import { eslintOverrides } from './overrides'

const hooksRules = <const>{
  'react-hooks/exhaustive-deps': 'error',
  'react-hooks/rules-of-hooks': 'error',
}

export const rules: EslintRules = {
  ...eslintOverrides,
  ...jsxA11yRules,
  ...hooksRules,
  'react/boolean-prop-naming': [
    'error',
    { rule: '^(is|has|should|can|did|will)[A-Z]([A-Za-z0-9]?)+' },
  ],
  'react/button-has-type': 'off', // revisit
  'react/default-props-match-prop-types': 'error',
  'react/destructuring-assignment': 'off',
  'react/display-name': 'warn',
  'react/forbid-component-props': 'off',
  'react/forbid-dom-props': 'off',
  'react/forbid-elements': 'off',
  'react/forbid-foreign-prop-types': 'off',
  'react/forbid-prop-types': [
    'error',
    {
      forbid: ['any', 'array', 'object'],
      checkContextTypes: true,
      checkChildContextTypes: true,
    },
  ],
  'react/function-component-definition': 'off',
  'react/hook-use-state': 'off', // revisit
  'react/iframe-missing-sandbox': 'off', // revisit
  'react/jsx-boolean-value': ['error', 'never'],
  'react/jsx-curly-brace-presence': 'off',
  'react/jsx-filename-extension': 'off',
  'react/jsx-fragments': ['error', 'syntax'],
  'react/jsx-handler-names': 'off',
  'react/jsx-key': 'warn',
  'react/jsx-max-depth': 'off',
  'react/jsx-no-bind': 'off',
  'react/jsx-no-comment-textnodes': 'warn',
  'react/jsx-no-constructed-context-values': 'error',
  'react/jsx-no-duplicate-props': ['error', { ignoreCase: true }],
  'react/jsx-no-leaked-render': 'off', // revisit
  'react/jsx-no-literals': 'off',
  'react/jsx-no-script-url': 'error',
  'react/jsx-no-target-blank': 'warn',
  'react/jsx-no-undef': 'warn',
  'react/jsx-no-useless-fragment': 'error',
  'react/jsx-one-expression-per-line': 'off',
  'react/jsx-pascal-case': 'error',
  'react/jsx-props-no-spreading': 'off',
  'react/jsx-sort-default-props': 'off',
  'react/jsx-sort-props': 'off',
  'react/jsx-uses-react': 'off',
  'react/jsx-uses-vars': 'warn',
  'react/no-access-state-in-setstate': 'error',
  'react/no-adjacent-inline-elements': 'warn',
  'react/no-array-index-key': 'off',
  'react/no-arrow-function-lifecycle': 'error',
  'react/no-children-prop': 'warn',
  'react/no-danger': 'off',
  'react/no-danger-with-children': 'warn',
  'react/no-deprecated': 'warn',
  'react/no-did-mount-set-state': 'error',
  'react/no-did-update-set-state': 'error',
  'react/no-direct-mutation-state': 'warn',
  'react/no-find-dom-node': 'warn',
  'react/no-invalid-html-attribute': 'error',
  'react/no-is-mounted': 'warn',
  'react/no-multi-comp': 'off',
  'react/no-namespace': 'error',
  'react/no-object-type-as-default-prop': 'off', // revisit
  'react/no-redundant-should-component-update': 'error',
  'react/no-render-return-value': 'warn',
  'react/no-set-state': 'off',
  'react/no-string-refs': 'warn',
  'react/no-this-in-sfc': 'error',
  'react/no-typos': 'error',
  'react/no-unescaped-entities': 'warn',
  'react/no-unknown-property': 'warn',
  'react/no-unsafe': 'off',
  'react/no-unstable-nested-components': 'error',
  'react/no-unused-class-component-methods': 'error',
  'react/no-unused-prop-types': 'error',
  'react/no-unused-state': 'error',
  'react/no-will-update-set-state': 'error',
  'react/prefer-es6-class': 'off',
  'react/prefer-exact-props': 'off', // revisit
  'react/prefer-read-only-props': 'off',
  'react/prefer-stateless-function': 'off',
  'react/prop-types': 'error',
  'react/react-in-jsx-scope': 'off',
  'react/require-default-props': 'off',
  'react/require-optimization': 'off',
  'react/require-render-return': 'warn',
  'react/self-closing-comp': 'error',
  'react/sort-comp': 'off',
  'react/sort-default-props': 'off', // revisit
  'react/sort-prop-types': 'off',
  'react/state-in-constructor': 'off',
  'react/static-property-placement': 'off',
  'react/style-prop-object': 'error',
  'react/void-dom-elements-no-children': 'error',
}
