name: pull_request

on: [pull_request]

jobs:
  code_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: pnpm/action-setup@6e1964dde3397a825e79e4607ad57f3f7ca2c7cb
        with:
          version: 6.21.1

      - name: setup cache ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: install
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm lint

      - name: format
        run: pnpm format

      - name: find new rules
        run: pnpm find-new-rules

      - name: test
        run: pnpm test:coverage

      - name: codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info

  commit_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: commitlint
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.yml

  spell_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: streetsidesoftware/cspell-action@v2.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          inline: error
